baseURL = 'https://mmkaram.github.io/'
languageCode = 'en-us'
title = "mmkaram"
theme = 'typo'

[params]
description = "My personal website"
favicon = false

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hello!'
homeIntroContent = """
My name is Mahdy Karam. I'm a student at the University of Waterloo. I like to write code and hit squash balls. I've been programming for 9 years and mostly code in python and C++. I play squash competitively and travel often for tournaments. Currently working on an app that can coach squash matches using computer vision</a>. Contact me on my LinkedIn if you want to collaborate!
"""

# Collection to display on home
homeCollectionTitle = 'Projects'
homeCollection = 'projects'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/mahdykaram/"

[[params.social]]
name = "github"
url = "https://github.com/mmkaram"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
